/* Generated By:JavaCC: Do not edit this line. MyParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyParserConstants {
    /** This flag lets the test know that this class is a custom AST class that was not generated by JavaCC. */
    public static final boolean IS_CUSTOM = true;

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ANYTHING = 2;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "<ANYTHING>",
  };

}
