package ca.coglinc.gradle.plugins.javacc;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import java.io.File;
import java.util.Arrays;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;

import org.gradle.api.Project;
import org.gradle.api.file.FileCollection;
import org.gradle.api.file.FileVisitor;
import org.gradle.api.file.RelativePath;
import org.gradle.api.tasks.TaskExecutionException;
import org.gradle.api.tasks.TaskValidationException;
import org.gradle.testfixtures.ProjectBuilder;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.mockito.Answers;
import org.mockito.Mockito;

public class CompileJavaccTaskTest {
    private static final String[] GENERATED_FILES = {"JavaccOutputTest.java", "JavaccOutputTestConstants.java", "JavaccOutputTestTokenManager.java",
        "ParseException.java", "SimpleCharStream.java", "Token.java", "TokenMgrError.java" };

    private CompileJavaccTask task;

    @Before
    public void setUp() {
        Project project = ProjectBuilder.builder().build();
        project.getRepositories().jcenter();
        applyJavaccPluginToProject(project);

        task = (CompileJavaccTask) project.getTasks().findByName(CompileJavaccTask.TASK_NAME_VALUE);
    }

    private void applyJavaccPluginToProject(Project project) {
        Map<String, String> pluginNames = new HashMap<String, String>(1);
        pluginNames.put("plugin", "ca.coglinc.javacc");

        project.apply(pluginNames);
    }

    @After
    public void tearDown() {
        final File outputDirectory = new File(getClass().getResource("/").getFile() + "output");
        if (outputDirectory.exists()) {
            deleteDirectories(outputDirectory);
        }
    }

    private void deleteDirectories(File outputDirectory) {
        for (File outputFile : outputDirectory.listFiles()) {
            if (outputFile.isDirectory()) {
                deleteDirectories(outputFile);
            } else {
                outputFile.delete();
            }
        }
        outputDirectory.delete();
    }

    @Test
    public void compileJavaccToJavaCompilesEachJavaccInputFileToJava() {
        setTaskInputDirectory("/javacc/inputWithSubFolder");
        final File outputDirectory = setTaskOutputDirectory("output");
        final File subOutputDirectory = new File(outputDirectory, "sub");

        task.execute();

        assertTrue(subOutputDirectory.isDirectory());
        assertEquals(CompileJavaccTaskTest.GENERATED_FILES.length, subOutputDirectory.list().length);
        assertTrue(Arrays.asList(subOutputDirectory.list()).containsAll(Arrays.asList(CompileJavaccTaskTest.GENERATED_FILES)));
    }

    @Test
    public void compileJavaccToJavaCompilesEachJavaccInputFileToJavaSubDirectory() {
        setTaskInputDirectory("/javacc/input");
        final File outputDirectory = setTaskOutputDirectory("output");

        task.execute();

        assertTrue(outputDirectory.isDirectory());
        assertEquals(CompileJavaccTaskTest.GENERATED_FILES.length, outputDirectory.list().length);
        assertTrue(Arrays.asList(outputDirectory.list()).containsAll(Arrays.asList(CompileJavaccTaskTest.GENERATED_FILES)));
    }

    @Test
    public void compileJavaccToJavaCopiesNonJavaccFilesToOutputDirectory() {
        setTaskInputDirectory("/javacc/inputWithNonJavaccFiles");
        final File outputDirectory = setTaskOutputDirectory("output");
        task.include("**/*.txt");

        task.execute();

        assertTrue(outputDirectory.isDirectory());
        assertEquals(1 + CompileJavaccTaskTest.GENERATED_FILES.length, outputDirectory.list().length);
        assertTrue(Arrays.asList(outputDirectory.list()).containsAll(Arrays.asList(CompileJavaccTaskTest.GENERATED_FILES)));
        assertTrue(Arrays.asList(outputDirectory.list()).containsAll(Arrays.asList("test.txt")));
    }

    @Test
    public void compileJavaccToJavaCompilesEachJavaccInputFileToJavaMultipleSources() {
        setTaskInputDirectory("/javacc/input");
        addTaskInputDirectory("/javacc/inputWithSubFolder");

        final File outputDirectory = setTaskOutputDirectory("output");

        task.execute();

        assertTrue(outputDirectory.isDirectory());
        // Generated files for /javacc/input + directory sub from files generated by /javacc/inputWithSubFolder/sub
        assertEquals(CompileJavaccTaskTest.GENERATED_FILES.length + 1, outputDirectory.list().length);
        assertTrue(Arrays.asList(outputDirectory.list()).containsAll(Arrays.asList(CompileJavaccTaskTest.GENERATED_FILES)));

        final File subOutputDirectory = new File(outputDirectory, "sub");
        assertTrue(subOutputDirectory.isDirectory());
        assertEquals(CompileJavaccTaskTest.GENERATED_FILES.length, subOutputDirectory.list().length);
        assertTrue(Arrays.asList(subOutputDirectory.list()).containsAll(Arrays.asList(CompileJavaccTaskTest.GENERATED_FILES)));
    }

    private File addTaskInputDirectory(final String inputDirectoryName) {
        final File inputDirectory = new File(getClass().getResource(inputDirectoryName).getFile());
        task.source(inputDirectory);

        return inputDirectory;
    }

    private File setTaskInputDirectory(final String inputDirectoryName) {
        final File inputDirectory = new File(getClass().getResource(inputDirectoryName).getFile());
        task.setInputDirectory(inputDirectory);

        return inputDirectory;
    }

    private File setTaskOutputDirectory(final String outputDirectoryName) {
        final File outputDirectory = new File(getClass().getResource("/").getFile() + outputDirectoryName);
        task.setOutputDirectory(outputDirectory);
        return outputDirectory;
    }

    @Test
    public void compileJavaccToJavaDoesNotGenerateAnythingIfNoInputFiles() {
        testExecuteTaskWithNoInputFiles(new File[0]);
    }

    private void testExecuteTaskWithNoInputFiles(File[] noInputFiles) {
        final File inputDirectory = Mockito.mock(File.class, Answers.RETURNS_MOCKS.get());
        Mockito.when(inputDirectory.listFiles()).thenReturn(noInputFiles);
        Mockito.when(inputDirectory.exists()).thenReturn(Boolean.TRUE);
        Mockito.when(inputDirectory.isDirectory()).thenReturn(Boolean.TRUE);
        task.setSource(inputDirectory);
        final File outputDirectory = new File(getClass().getResource("/").getFile() + "output");
        task.setOutputDirectory(outputDirectory);

        task.execute();

        assertFalse(outputDirectory.isDirectory());
    }

    @Test
    public void compileJavaccToJavaDoesNotGenerateAnythingIfInputFilesNull() {
        testExecuteTaskWithNoInputFiles(null);
    }

    @Test
    public void compileJavaccToJavaCompilesEachJavaccInputFileToJavaIntoItsPackage() {
        setTaskInputDirectory("/javacc/inputWithPackages");
        final File outputDirectory = setTaskOutputDirectory("output");

        task.execute();

        assertTrue(outputDirectory.isDirectory());
        assertEquals(1, outputDirectory.list().length);
        assertEquals("test", outputDirectory.list()[0]);
        final String[] filesInTestPackageUnderOutputDirectory = outputDirectory.listFiles()[0].list();
        assertEquals(CompileJavaccTaskTest.GENERATED_FILES.length, filesInTestPackageUnderOutputDirectory.length);
        assertTrue(Arrays.asList(filesInTestPackageUnderOutputDirectory).containsAll(Arrays.asList(CompileJavaccTaskTest.GENERATED_FILES)));
    }

    @Test(expected = TaskExecutionException.class)
    public void compileJavaccFailsWhenParserGeneratesAnError() {
        setTaskInputDirectory("/javacc/inputWithErrors");
        setTaskOutputDirectory("output");

        task.execute();
    }

    @Test(expected = IllegalArgumentException.class)
    public void inputDirectoryIsMandatory() {
        task.setSource(null);
        setTaskOutputDirectory("output");

        task.execute();
    }

    @Test(expected = TaskValidationException.class)
    public void outputDirectoryIsMandatory() {
        setTaskInputDirectory("/javacc/input");
        task.setOutputDirectory((File) null);

        try {
            task.execute();
        } catch (TaskExecutionException e) {
            assertTrue(e.getCause() instanceof IllegalArgumentException);
            throw e;
        }
    }

    @Test
    public void taskInputsAreInputDirectory() {
        setTaskInputDirectory("/javacc/input");

        task.execute();

        FileCollection inputFiles = task.getInputs().getFiles();
        assertEquals(1, inputFiles.getFiles().size());
        assertEquals("JavaccOutputTest.jj", ((File) inputFiles.getFiles().toArray()[0]).getName());
    }

    @Test
    public void taskOutputsAreOutputDirectory() {
        setTaskInputDirectory("/javacc/input");
        setTaskOutputDirectory("output");

        task.execute();

        FileCollection outputFiles = task.getOutputs().getFiles();
        assertEquals(1, outputFiles.getFiles().size());
        assertEquals("output", ((File) outputFiles.getFiles().toArray()[0]).getName());
    }

    @Test
    public void argumentsGetterSetter() {
        Map<String, String> expectedArguments = new HashMap<String, String>();
        expectedArguments.put("static", "false");
        task.setArguments(expectedArguments);

        Map<String, String> arguments = task.getArguments();

        assertEquals(expectedArguments, arguments);
    }

    @Test
    public void javaccArgumentsAreOutputDirectoryAndFileToCompileWhenNoJavaccArgumentsProvided() {
        File inputDirectory = setTaskInputDirectory("/javacc/input");
        File outputDirectory = setTaskOutputDirectory("output");
        File tempOutputDirectory = new File(outputDirectory, "tmp");

        RelativePath inputRelativePath = Mockito.mock(RelativePath.class);
        Mockito.when(inputRelativePath.getPathString()).thenReturn("Grammar.jj");
        Mockito.when(inputRelativePath.getFile(inputDirectory)).thenReturn(new File(inputDirectory, "Grammar.jj"));
        Mockito.when(inputRelativePath.getFile(tempOutputDirectory)).thenReturn(new File(tempOutputDirectory, "Grammar.jj"));

        ProgramArguments javaccArgumentsForCommandLine = task.buildProgramArguments(inputDirectory, inputRelativePath);

        assertEquals(2, javaccArgumentsForCommandLine.size());
        assertEquals("-OUTPUT_DIRECTORY=" + tempOutputDirectory.getAbsolutePath(), javaccArgumentsForCommandLine.get(0));
    }

    @Test
    public void javaccArgumentsAreOutputDirectoryAndFileToCompileWhenEmptyJavaccArgumentsProvided() {
        File inputDirectory = setTaskInputDirectory("/javacc/input");
        File outputDirectory = setTaskOutputDirectory("output");
        File tempOutputDirectory = new File(outputDirectory, "tmp");

        RelativePath inputRelativePath = Mockito.mock(RelativePath.class);
        Mockito.when(inputRelativePath.getPathString()).thenReturn("Grammar.jj");
        Mockito.when(inputRelativePath.getFile(inputDirectory)).thenReturn(new File(inputDirectory, "Grammar.jj"));
        Mockito.when(inputRelativePath.getFile(tempOutputDirectory)).thenReturn(new File(tempOutputDirectory, "Grammar.jj"));

        task.setArguments(new HashMap<String, String>(0));

        ProgramArguments javaccArgumentsForCommandLine = task.buildProgramArguments(inputDirectory, inputRelativePath);

        assertEquals(2, javaccArgumentsForCommandLine.size());
        assertEquals("-OUTPUT_DIRECTORY=" + tempOutputDirectory.getAbsolutePath(), javaccArgumentsForCommandLine.get(0));
    }

    @Test
    public void javaccArgumentsAreOutputDirectoryFileToCompileAndProvidedArguments() {
        File inputDirectory = setTaskInputDirectory("/javacc/input");
        File outputDirectory = setTaskOutputDirectory("output");
        File tempOutputDirectory = new File(outputDirectory, "tmp");

        RelativePath inputRelativePath = Mockito.mock(RelativePath.class);
        Mockito.when(inputRelativePath.getPathString()).thenReturn("Grammar.jj");
        Mockito.when(inputRelativePath.getFile(inputDirectory)).thenReturn(new File(inputDirectory, "Grammar.jj"));
        Mockito.when(inputRelativePath.getFile(tempOutputDirectory)).thenReturn(new File(tempOutputDirectory, "Grammar.jj"));

        LinkedHashMap<String, String> javaccArguments = new LinkedHashMap<String, String>(1);
        javaccArguments.put("static", Boolean.FALSE.toString());
        task.setArguments(javaccArguments);

        ProgramArguments javaccArgumentsForCommandLine = task.buildProgramArguments(inputDirectory, inputRelativePath);

        final int outputDirectoryAndProvidedArgumentAndFileToCompile = 3;
        assertEquals(outputDirectoryAndProvidedArgumentAndFileToCompile, javaccArgumentsForCommandLine.size());
        assertEquals("-OUTPUT_DIRECTORY=" + tempOutputDirectory.getAbsolutePath(), javaccArgumentsForCommandLine.get(1));
    }

    @Test
    public void getFileVisitorReturnsInstanceOfJavaccSourceFileVisitor() {
        FileVisitor sourceFileVisitor = task.getJavaccSourceFileVisitor();

        assertTrue(sourceFileVisitor instanceof JavaccSourceFileVisitor);
    }

    @Test
    public void supportsDotJjFiles() {
        String supportedSuffix = task.supportedSuffix();

        assertEquals(".jj", supportedSuffix);
    }
}
