/* Generated By:JavaCC: Do not edit this line. JavaccOutputTestConstants.java */
package testgenerated;

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JavaccOutputTestConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ABS = 1;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"abs\"",
  };

}
