/* Generated By:JavaCC: Do not edit this line. HelloTreeConstants.java Version 6.1_2 */
package AST;

public interface HelloTreeConstants
{
    /** This flag lets the test know that this class is a custom AST class that was not generated by JavaCC. */
    public static final boolean IS_CUSTOM = true;
    
  public int JJTSTART = 0;


  public String[] jjtNodeName = {
    "Start",
  };
}
/* JavaCC - OriginalChecksum=0f40fb0fb8fca446f7cc96c60759df1f (do not edit this line) */
