name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 8, 11 ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.version }}
        distribution: 'temurin'
    - name: Run build script
      run: ./gradlew build
      shell: bash
    - name: checkstyle
      uses: dbelyaev/action-checkstyle@v0.7.4
      with:
        github_token: ${{ secrets.github_token }}
        checkstyle_config: 'config/checkstyle/checks.xml'
        reporter: github-check
        level: warning
