/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'FrancisANDRE' at '03/11/16 07:08' with Gradle 3.3-20161014182032+0000
 *
 * @author FrancisANDRE, @date 03/11/16 07:08
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
